name: "Deploy Release"

on:
  push:
    tags:
      - '*'

jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            driver: docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build - Base
        uses: docker/build-push-action@v5
        with:
          context: ./00-base
          file: 00-base/Dockerfile
          push: true
          tags: edulinq/autograder.base:${{ github.ref_name }}

      - name: Build - Python
        uses: docker/build-push-action@v5
        with:
          context: ./10-python
          file: 10-python/Dockerfile
          push: true
          tags: edulinq/autograder.python:${{ github.ref_name }}
