name: "Deploy Latest"

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main

jobs:
  on-success:

    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build - Base - Ubuntu
        uses: docker/build-push-action@v6
        with:
          context: ./00-base/ubuntu
          file: 00-base/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: edulinq/grader.base:latest,edulinq/grader.base-ubuntu:latest,edulinq/grader.base-ubuntu22.04:latest

      - name: Build - Base - Alpine
        uses: docker/build-push-action@v6
        with:
          context: ./00-base/alpine
          file: 00-base/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: edulinq/grader.base-alpine:latest,edulinq/grader.base-alpine3.20.3:latest

      - name: Build - Python - Ubuntu
        uses: docker/build-push-action@v6
        with:
          context: ./10-python/ubuntu
          file: 10-python/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: edulinq/grader.python:latest,edulinq/grader.python-ubuntu:latest,edulinq/grader.python-ubuntu22.04:latest

      - name: Build - Python - Alpine
        uses: docker/build-push-action@v6
        with:
          context: ./10-python/alpine
          file: 10-python/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: edulinq/grader.python-alpine:latest,edulinq/grader.python-alpine3.20.3:latest
