name: Main

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build - Base
        uses: docker/build-push-action@v5
        with:
          context: ./00-base
          file: 00-base/Dockerfile
          push: false
          load: true
          tags: eriqaugustine/autograder.base:latest

      - name: TEST - List Images
        run: docker images -a

      - name: Build - Python
        uses: docker/build-push-action@v5
        with:
          context: ./10-python
          file: 10-python/Dockerfile
          push: false
          tags: eriqaugustine/autograder.python:latest
