name: Test

on:
  - push
  - pull_request

jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            driver: docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build - Base - Ubuntu
        uses: docker/build-push-action@v6
        with:
          context: ./00-base/ubuntu
          file: 00-base/ubuntu/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          build-args: |
            BASE_TAG=test
          tags: edulinq/grader.base-ubuntu:test

      - name: Build - Base - Alpine
        uses: docker/build-push-action@v6
        with:
          context: ./00-base/alpine
          file: 00-base/alpine/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          build-args: |
            BASE_TAG=test
          tags: edulinq/grader.base-alpine:test

      - name: Build - Python - Ubuntu
        uses: docker/build-push-action@v6
        with:
          context: ./10-python/ubuntu
          file: 10-python/ubuntu/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          build-args: |
            BASE_TAG=test
          tags: edulinq/grader.python-ubuntu:test

      - name: Build - Python - Alpine
        uses: docker/build-push-action@v6
        with:
          context: ./10-python/alpine
          file: 10-python/alpine/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          build-args: |
            BASE_TAG=test
          tags: edulinq/grader.python-alpine:test
